/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 photoreal_earth.gltf 
*/


import { useGLTF, PerspectiveCamera, OrthographicCamera } from '@react-three/drei'

function Model(props) {
  const { nodes,errors } = useGLTF('/photoreal_earth.gltf')
  console.log('Model component rendered');

  console.log('GLTF nodes:', nodes);
  console.log('GLTF errors:', errors);
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[-1291, 0, 112]}>
          <group rotation={[0, Math.PI / 2, 0]}>
            <directionalLight intensity={1} decay={2} rotation={[0, 0.426, 0]} />
          </group>
          <mesh
            geometry={nodes.Atmosphere.geometry}
            material={nodes.Atmosphere.material}
            position={[0, 0, 1]}
            scale={1.04}
          />
          <mesh geometry={nodes.Earth.geometry} material={nodes.Earth.material} />
        </group>
        <OrthographicCamera
          makeDefault={false}
          far={100000}
          near={0}
          position={[8875.015, -1003.811, -38110.257]}
          rotation={[1.571, 0, 0]}
        />
        <PerspectiveCamera makeDefault={false} far={1000000} near={70} fov={45} position={[0, 0, 201025.964]} />
        <mesh
          geometry={nodes.Stars.geometry}
          material={nodes.Stars.material}
          position={[0, 0, -148355.288]}
          scale={20}
        />
      </group>
    </group>
  )
}
export default Model
useGLTF.preload('/photoreal_earth.gltf')
